# Generated by Django 6.1.1 on 2026-09-10 01:50

import Gestion_clientes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de notificación')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=150, verbose_name='Marca y modelo del dispositivo')),
                ('descripcion_dano', models.TextField(verbose_name='Descripción del daño / síntomas')),
                ('valor_reparacion', models.PositiveIntegerField(default=0, verbose_name='Valor de la reparación (COP)')),
                ('abono_inicial', models.PositiveIntegerField(default=0, verbose_name='Abono inicial (COP)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Gestion_clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FotoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=Gestion_clientes.models.ruta_foto_orden, verbose_name='Foto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='Gestion_clientes.ordenservicio')),
            ],
        ),
    ]
